name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Build and deploy
        run: |
          git config --global user.name "Daniel"
          git config --global user.email "nifemiolaniyi4@gmail.com"
          npm run build
          npm run deploy
